language: node_js
node_js:
  - 8
install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y php7.0 php7.0-mbstring php7.0-xml

# Install Image and Video/GIF Manipulation Tools
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo add-apt-repository -y ppa:jamedjo/ppa
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg imagemagick pngquant gifsicle webp

  - npm install
  
script:
  - make
